server: client_write.cpp client_basical.hpp ../common/con_hash.hpp ../common/json.hpp ../common/LRU.hpp ../common/threadpool.hpp ../common/wrap_fun.hpp

		g++ -o client_write $^ -lpthread

clean: 
		rm -r client_write
