server: cache_server.cpp cache_server.hpp HeartBeat.hpp WriteRead.hpp ../common/con_hash.hpp ../common/threadpool.hpp ../common/wrap_fun.hpp ../common/json.hpp ../common/LRU.hpp

		g++ -o cache1 $^ -lpthread

clean: 
		rm -r cache1