server: master_main.cpp master_basical.hpp ../common/con_hash.hpp ../common/json.hpp ../common/LRU.hpp ../common/threadpool.hpp ../common/wrap_fun.hpp

		g++ -o master $^ -lpthread

clean: 
		rm -r master